version: '3.8'

services:
  mysql-master:
    build: ./master
    container_name: routemate-mysql-master
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: routemate_db
    ports:
      - "3307:3306"
    networks:
      - mysql-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 5s
      retries: 20

  mysql-slave-1:
    build: ./slave1
    container_name: routemate-mysql-slave-1
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3308:3306"
    depends_on:
      mysql-master:
        condition: service_healthy
    networks:
      - mysql-network

  mysql-slave-2:
    build: ./slave2
    container_name: routemate-mysql-slave-2
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3309:3306"
    depends_on:
      mysql-master:
        condition: service_healthy
    networks:
      - mysql-network

networks:
  mysql-network:
    driver: bridge
