version: '3.8'
services:
  mysql-master:
    image: mysql:8.0
    container_name: routemate-mysql-master
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: routemate_db
    ports:
      - "3307:3306"
    command: --default-authentication-plugin=mysql_native_password

  mysql-slave-1:
    image: mysql:8.0
    container_name: routemate-mysql-slave-1
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: routemate_db
    ports:
      - "3308:3306"
    command: --default-authentication-plugin=mysql_native_password

  mysql-slave-2:
    image: mysql:8.0
    container_name: routemate-mysql-slave-2
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: routemate_db
    ports:
      - "3309:3306"
    command: --default-authentication-plugin=mysql_native_password
