spring:
  application:
    name: routemate-example
  datasource:
    url: jdbc:mysql://localhost:3307/routemate_db
      ?useSSL=false
      &allowPublicKeyRetrieval=true
      &serverTimezone=UTC
    username: routemate
    password: routemate
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

routemate:
  enabled: true
  reads:
    slave-1:
      url: jdbc:mysql://localhost:3308/routemate_db
        ?useSSL=false
        &allowPublicKeyRetrieval=true
        &serverTimezone=UTC
      username: routemate
      password: routemate
      driver-class-name: com.mysql.cj.jdbc.Driver
      weight: 1
    slave-2:
      url: jdbc:mysql://localhost:3309/routemate_db
        ?useSSL=false
        &allowPublicKeyRetrieval=true
        &serverTimezone=UTC
      username: routemate
      password: routemate
      driver-class-name: com.mysql.cj.jdbc.Driver
      weight: 1
  routing:
    load-balance-strategy: weighted-round-robin

logging:
  level:
    root: info
